# Generated by Django 5.2.6 on 2025-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotes",
            old_name="added_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="quotes",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
