# Generated by Django 5.2.6 on 2025-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_added_date_quotes_created_at_quotes_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
